### ISSUE TITLE
Goto Symbol 的问题

### ISSUE THREAD

**Issue by wetiontop** [wonyee/vscode-cocoslua#1]
你好，我发现Goto Symbol有个问题，就是我必须修改过这个lua文件后这个文件的函数才能被跳转？我想打开lua项目后就可以在外部跳转所有的函数改如何做。

**Comment by wonyee** [comment]
我这里测试没发现这个问题
我想了下可能的原因有：1.文件有lua error导致该文件的symbol无法被goto 2.一打开vscode就goto，这时候symbol还没parse完。可以等几秒等parse完成后再试试。 3.vscode版本不是最新之类的？

**Comment by wetiontop** [comment]
![aug-09-2018 12-21-11](https://user-images.githubusercontent.com/4017034/43877904-d5a090cc-9bce-11e8-8b99-300d921774ee.gif)
我做了个gif,我打开一个没修改过的lua文件，cmd+鼠标左键是没有跳转提示的，后面我修改了一行代码，再用cmd+鼠标左键就有跳转提示了。你上面提到的原因：1、我的项目是可以运行的，如果有语法错误就运行不了了。2、我的vscode已经打开好久了，基本几天不关机的。3、我的vscode是最新版本的。

**Comment by wetiontop** [comment]
补充下，我的系统是macos最新版本

**Comment by wonyee** [comment]
我大致明白了，是一个缺陷。现在我都是针对文件夹、工作区来做代码解析的。你估计是以打开单个文件的形式打开的，没有自动解析。
我当时的思路是，直接打开lua代码文件夹/工作区，可以跨文件提示什么的更方便，却漏掉了打开单个lua文件这个需求-_-
你可以试试，用打开文件夹的形式，直接打开你项目中包含lua的目录。
至于这个问题我会抽空修复掉。
感谢反馈问题

**Comment by wetiontop** [comment]
好的，也感谢你让我们使用你开发的插件。
